/**
 * The canary: before the agent starts, the policy is tried from inside.
 *
 * The settings are generated by software, and software breaks. A runtime
 * upgrade, a path that turned out to be a symlink, an `isolate` level combined
 * with something it was not measured with — any of them can leave a door open,
 * and without this the first anyone hears of it is after something went
 * through it. So every run starts with a short process under the SAME runtime,
 * the SAME settings file and the SAME environment as the agent, and the agent
 * starts only if every answer is the expected one.
 *
 * Judged by effect, never by exit code: a write "denied" is a file that is not
 * there afterwards; a read "denied" is a nonce that never came out; a
 * connection "refused" is a nonce the decoy never delivered. And each denial
 * has a positive control beside it — the sandbox ran at all, and a place the
 * role may write took the write — because a sandbox that runs nothing denies
 * everything too.
 *
 * **Fails closed, including on a missing tool.** In an orchestrator we compared against, the network
 * probe passed whenever `nc` was absent: no tool, no connection, "refused".
 * Here a probe that cannot be made is a failed canary.
 *
 * **No flag skips it.** A flag becomes an alias, and the alias becomes the way
 * every run starts. It costs one extra start of the runtime, a few tenths of a
 * second, against a run that lasts minutes.
 */
import { spawn } from "node:child_process";
import { createServer } from "node:net";
import { randomBytes } from "node:crypto";
import { writeFileSync, readFileSync, rmSync, existsSync, statSync } from "node:fs";
import { join, dirname } from "node:path";

/** The exit code of a run the canary stopped: not the agent's, and not one a shell uses. */
export const CANARY_EXIT = 86;

const isDir = (p) => { try { return statSync(p).isDirectory(); } catch { return false; } };

/**
 * Runs the canary and resolves to `{ ok, failed: [reasons], ms }`.
 *
 * `runDir` is this run's directory and `runsRoot` the one above it; the
 * secret is planted in the second, which the settings deny to every run but
 * the run's own directory. `role.localBinding` skips the network probe and
 * says so: that role was granted every localhost port on purpose.
 */
export async function runCanary({ srt, settingsFile, settings, env, cwd, runDir, runsRoot, role, granted, timeoutMs = 20_000 }) {
  const t0 = Date.now();
  const nonce = randomBytes(8).toString("hex");
  const failed = [];

  const secret = join(runsRoot, `canary-${nonce}.secret`);
  const outside = join(runDir, `canary-${nonce}.out`);
  // The first directory the POLICY grants that exists — taken from the
  // policy and not from the settings, so settings that lost the grant fail
  // here instead of skipping the check. Absent (a role with nothing to
  // write), the write control is skipped and "the sandbox ran" stands alone.
  // Outside the repo first (the runtime's scratch, the role's home): a file
  // appearing and vanishing in a watched tree restarts a dev server.
  const candidates = (granted ?? settings.filesystem.allowWrite ?? []).filter((p) => isDir(p));
  const writable = candidates.find((p) => !(cwd && (p === cwd || p.startsWith(cwd + "/") || cwd.startsWith(p + "/")))) ?? candidates[0];
  const inside = writable ? join(writable, `.seisin-canary-${nonce}`) : null;
  const policy = settingsFile;

  writeFileSync(secret, `SECRET-${nonce}\n`, { mode: 0o600 });

  let server = null;
  let port = null;
  if (!role.localBinding) {
    server = createServer((s) => s.end(`HTTP/1.0 200 OK\r\nContent-Type: text/plain\r\n\r\nNET-${nonce}\n`));
    await new Promise((res, rej) => server.listen(0, "127.0.0.1", res).on("error", rej));
    port = server.address().port;
  }

  const q = (s) => `'${String(s).replace(/'/g, `'\\''`)}'`;
  const script = [
    `echo ALIVE-${nonce}`,
    `(echo x > ${q(outside)}) 2>/dev/null`,
    `cat ${q(secret)} 2>/dev/null`,
    `cat ${q(policy)} >/dev/null 2>&1 && echo POLICY-READ-${nonce}`,
    inside ? `(echo IN-${nonce} > ${q(inside)}) 2>/dev/null` : ":",
    port ? `if command -v curl >/dev/null 2>&1; then curl -s -m 3 http://127.0.0.1:${port}/ 2>/dev/null; else echo NO-CURL-${nonce}; fi` : ":",
  ].join("; ");

  let output = "";
  let timedOut = false;
  try {
    const status = await new Promise((resolve) => {
      const child = spawn(srt, ["--settings", settingsFile, "--", "/bin/sh", "-c", script], {
        cwd, env, stdio: ["ignore", "pipe", "pipe"],
      });
      const timer = setTimeout(() => { timedOut = true; try { child.kill("SIGKILL"); } catch {} }, timeoutMs);
      child.stdout.on("data", (d) => { output += d; });
      child.stderr.on("data", () => {});
      child.on("error", () => { clearTimeout(timer); resolve(null); });
      child.on("close", (code) => { clearTimeout(timer); resolve(code); });
    });
    void status;
  } finally {
    server?.close();
  }

  if (timedOut) failed.push(`the canary did not finish in ${timeoutMs / 1000}s`);
  if (!output.includes(`ALIVE-${nonce}`)) failed.push("the sandbox did not run the canary at all");
  if (existsSync(outside)) failed.push(`a write outside the territory went through (${outside})`);
  if (output.includes(`SECRET-${nonce}`)) failed.push(`a planted secret was readable (${secret})`);
  if (output.includes(`POLICY-READ-${nonce}`)) failed.push(`the run's own settings were readable (${policy})`);
  if (inside) {
    let wrote = false;
    try { wrote = readFileSync(inside, "utf8").trim() === `IN-${nonce}`; } catch {}
    if (!wrote) failed.push(`a write the role is granted did not go through (${dirname(inside)}) — the positive control`);
  }
  if (port) {
    if (output.includes(`NO-CURL-${nonce}`)) failed.push("no curl inside the sandbox to probe the network with — a probe that cannot be made is not a pass");
    if (output.includes(`NET-${nonce}`)) failed.push(`a loopback port outside the policy was reachable (127.0.0.1:${port})`);
  }

  for (const p of [secret, outside, inside]) if (p) try { rmSync(p, { force: true }); } catch {}
  return { ok: failed.length === 0, failed, ms: Date.now() - t0 };
}
